### ISSUE TITLE
Missing dependency check at configure: zstd

### ISSUE THREAD

**Issue by trahay** [pmodels/pilgrim#24]
I tried compiling Pilgrim on a machine where `libzstd` was not installed. The configure script worked fine, but the compilation failed with the followong error:

```
  CC       src/pilgrim_timings.lo
../src/pilgrim_timings.c:11:10: fatal error: zstd.h: No such file or directory
   11 | #include "zstd.h"
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:837 : src/pilgrim_timings.lo] Erreur 1
```

I fixed the problem by installing `libzstd-dev`. However, it would be better to check for `zstd.h` in the `configure.ac` script.

**Comment by wangvsa** [comment]
Thank you. Added the dependency check in the new [PR](https://github.com/pmodels/pilgrim/pull/25).
