### ISSUE TITLE
Not working with openmpi, MPI_Comm_size

### ISSUE THREAD

**Issue by marcocrxu** [pmodels/pilgrim#27]
Not working with openmpi due to MPI_Comm problem.
I removed MPI_Aint_diff and MPI_Aint_add from pilgrim_wrappers.c and build pilgrim with openmpi-3.1.0 successfully. Then I can use  pilgrim to trace some easy mpi-job. 
However, when I use MPI_Comm_split in my mpi program, I get a communicatr error in MPI_Comm_size which is just after MPI_Comm_split. 
It seems pilgrim implement another MPI_Comm_split after invoking PMPI_Comm_split in real MPI lib? 
I'd like to know if it possible to fix this?

<img width="772" alt="image" src="https://user-images.githubusercontent.com/44637336/224599142-12a6159f-8348-4b22-99d7-200823bf6dc5.png">

**Comment by wangvsa** [comment]
Hi @marcocrxu is it possible to share your code for me to debug?

**Comment by marcocrxu** [comment]
> Hi @marcocrxu is it possible to share your code for me to debug?

My code is NPB-3.3.1, bt.C.16. I found this problem was caused by MPI_Comm_split's fortran interface, which don't convert newcomm to MPI_Fint.  
The following code could solve this problem.
```
extern void MPI_COMM_SPLIT(MPI_Fint* comm, int* color, int* key, MPI_Fint* newcomm, MPI_Fint *ierr){ MPI_Comm c_comm_out; imp_MPI_Comm_split(PMPI_Comm_f2c(*comm), (*color), (*key), &c_comm_out); *newcomm = MPI_Comm_c2f(c_comm_out);}
extern void mpi_comm_split(MPI_Fint* comm, int* color, int* key, MPI_Fint* newcomm, MPI_Fint *ierr){ MPI_Comm c_comm_out; imp_MPI_Comm_split(PMPI_Comm_f2c(*comm), (*color), (*key), &c_comm_out); *newcomm = MPI_Comm_c2f(c_comm_out);}
extern void mpi_comm_split_(MPI_Fint* comm, int* color, int* key, MPI_Fint* newcomm, MPI_Fint *ierr){ MPI_Comm c_comm_out; imp_MPI_Comm_split(PMPI_Comm_f2c(*comm), (*color), (*key), &c_comm_out); *newcomm = MPI_Comm_c2f(c_comm_out);}
extern void mpi_comm_split__(MPI_Fint* comm, int* color, int* key, MPI_Fint* newcomm, MPI_Fint *ierr){ MPI_Comm c_comm_out; imp_MPI_Comm_split(PMPI_Comm_f2c(*comm), (*color), (*key), &c_comm_out); *newcomm = MPI_Comm_c2f(c_comm_out);}
```
After fix this, I get a new invalid datatype problem when the program call MPI_Bcast. 
<img width="424" alt="image" src="https://user-images.githubusercontent.com/44637336/224878033-9882a5f5-6347-4ec5-bd59-13fcc225faad.png">
The dptype here is set by the following code. Do you have any idea how to fix this? Many thaks.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/44637336/224878139-c1641c07-a998-4325-b6fb-4e8ec3d1c791.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/44637336/224878392-1267195f-a041-475a-abcd-2a3dc54e5798.png">

**Comment by wangvsa** [comment]
I see, we were mostly testing with MPICH. If you're in a hurry, you could try using MPICH. In the meantime, I'll look into this issue and get back asap.

**Comment by marcocrxu** [comment]
Many thanks. This helps me a lot.
