### ISSUE TITLE
Autogen.sh failing

### ISSUE THREAD

**Issue by mhaseeb123** [pmodels/pilgrim#34]
Hi,
I am trying to compile pilgrim on my machine using the steps from the repo README but I am getting `m4` related errors while running the `autogen.sh`. Please see the attached screenshot showing the error as well as my currently loaded modules. I would appreciate it if someone could help 🙂

Error message:
```bash
configure.ac:111: error: possibly undefined macro: AC_MSG_WARN
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

```
<img width="1248" alt="image" src="https://github.com/pmodels/pilgrim/assets/14217455/d92a3c2a-910c-4d39-a458-c0c70b2730d6">

P.S. I have already built the `SZ` and `ZFS` libraries and plan to build `pilgrim` with them as well.

**Comment by wangvsa** [comment]
This is likely a autoconf issue, probably due to the missing of "pkg-config" package. Can you check if your machine has "m4" and "pkg-config" commands?

A temporary fix you can try is to delete lines 109-112 of configure.ac.

**Comment by mhaseeb123** [comment]
Thank you for getting back @wangvsa. The machine does have both commands as shown in screenshot.
<img width="619" alt="image" src="https://github.com/pmodels/pilgrim/assets/14217455/97cf403e-472c-47ff-a3b8-8bd7ab8af62d">

Thankfully the temporary fix did work for now but now I am getting `multiple definition linker errors` while as there are following global variables in `pilgrim_logger.h` and `pilgrim_pthread_hooks.h`

```cpp
// Global variables
int g_mpi_rank;
int g_mpi_size;
double g_program_start_time;
```
<img width="951" alt="image" src="https://github.com/pmodels/pilgrim/assets/14217455/9f0a36aa-caf0-48b5-8097-9bf33037e40e">

Marking these variables `static` does the job but I am not sure if this will break any functionality?

**Comment by wangvsa** [comment]
Strange, I have never seen undefined macro error before.
Adding static should not break any functionality.

**Comment by mhaseeb123** [comment]
It's not an undefined macro, but a `redefinition of variables` the macros are exapanding to. Thanks for the update, I will proceed with making these global vars `static`
