### ISSUE TITLE
Understanding pilgrim's output and logs

### ISSUE THREAD

**Issue by mhaseeb123** [pmodels/pilgrim#35]
Hi,
I have been trying to search information on how to read/interpret pilgrim's output (e.g. the following log) and the `.dat` log files in the created `pilgrim-log` which are in binary format. I would appreciate it if you could provide any information or point me to a page/link where I can find it. Thank you!

```bash
#input
export PILGRIM_DEBUG=0
export LD_PRELOAD=/global/cfs/cdirs/m1759/mhaseeb/pilgrim/gnu/install/lib/libpilgrim.so
export PILGRIM_TIMING_MODE=ZSTD
export PILGRIM_TRACING=ON

srun -n 4 -c 1 /global/cfs/cdirs/m1759/mhaseeb/pilgrim/pilgrim/test/mpi/pt2pt/sendall

#output
 No Errors
MPI_Comm_size, 1, 1
MPI_Send, 45, 450
MPI_Comm_rank, 1, 2
MPI_Reduce, 1, 1
MPI_Wait, 3, 450
MPI_Barrier, 1, 165
MPI_Irecv, 45, 450
ZSTD compression ratio: 2.945939
[pilgrim] Current memory usage: 48680, Peak memory usage: 170678
[pilgrim] Total mpi calls: 0.006076 *1e6
[pilgrim] CST inter-process compression time: 0.01
[pilgrim] CFG inter-process compression time: 0.00
[pilgrim] CST Size: 6.97KB, CFG Size: 1.43KB, Total: 8.40KB
MPI_Comm_size, 1, 1
MPI_Send, 45, 450
MPI_Comm_rank, 1, 2
MPI_Reduce, 1, 1
MPI_Wait, 3, 450
MPI_Barrier, 1, 165
MPI_Irecv, 45, 450
ZSTD compression ratio: 2.881669
[pilgrim] Current memory usage: 48680, Peak memory usage: 164178
[pilgrim] Total mpi calls: 0.000000 *1e6
[pilgrim] CST inter-process compression time: 0.01
[pilgrim] CFG inter-process compression time: 0.00
[pilgrim] CST Size: 6.97KB, CFG Size: 0.00KB, Total: 6.97KB
MPI_Comm_size, 1, 1
MPI_Send, 45, 450
MPI_Comm_rank, 1, 2
MPI_Reduce, 1, 1
MPI_Wait, 3, 450
MPI_Barrier, 1, 165
MPI_Irecv, 45, 450
ZSTD compression ratio: 2.935975
[pilgrim] Current memory usage: 48680, Peak memory usage: 164178
[pilgrim] Total mpi calls: 0.000000 *1e6
[pilgrim] CST inter-process compression time: 0.01
[pilgrim] CFG inter-process compression time: 0.00
[pilgrim] CST Size: 6.97KB, CFG Size: 0.00KB, Total: 6.97KB
MPI_Comm_size, 1, 1
MPI_Send, 45, 450
MPI_Comm_rank, 1, 2
MPI_Reduce, 1, 1
MPI_Wait, 3, 450
MPI_Barrier, 1, 165
MPI_Irecv, 45, 450
ZSTD compression ratio: 2.860640
[pilgrim] Current memory usage: 48680, Peak memory usage: 164178
[pilgrim] Total mpi calls: 0.000000 *1e6
[pilgrim] CST inter-process compression time: 0.01
[pilgrim] CFG inter-process compression time: 0.00
[pilgrim] CST Size: 6.97KB, CFG Size: 0.00KB, Total: 6.97KB

```

**Comment by mhaseeb123** [comment]
Thank you for this. I tried using the `pilgrim2text` tool but I get the following error. I haven't been able to use it with the outputs from other `PILGRIM_TIMING_MODE`s due to #36 but I can give it a go. Any suggestions for the `ZSDT` compressed logs?

<img width="736" alt="image" src="https://github.com/pmodels/pilgrim/assets/14217455/28efee71-fac1-4e97-8ede-0f28822b6741">

**Comment by wangvsa** [comment]
Oh, pilgrim2text currently only supports reading traces that were stored in LOSSLESS mode. It should be easy to support ZSTD. Are you in particular interested in ZSTD or want to test different compression modes, or want to exam the MPI traces in general?

**Comment by mhaseeb123** [comment]
I am interesting in MPI traces in general. Since currently only ZSTD was properly working for me, so I was focusing on that but the `LOSSLESS` or any other modes should be good for now!

**Comment by wangvsa** [comment]
The pilgrim traces store near-lossless MPI information, including function name and all call parameters. But pilgirm2text only prints out the function name, entry/exit timestamp of every function call.

**Comment by mhaseeb123** [comment]
Thank you for the information. I was able to use `pilgrim2text` on the output logs from `LOSSLESS` mode to print out the timestamps and function names like you mentioned. I think I also figured out how to modify it to get more info out of the `CallSignature` data structure.

**Comment by wangvsa** [comment]
No problem. Let me know if need more information.

**Comment by victorsndvg** [comment]
Thanks @wangvsa for your great job with this lib! :)

I'm starting to play with it and, in addition to timestamps and function names, I would like to get the arguments too.

I don't know how to modify your code. So, if you think it could fit in your code, could you provide a way to print the arguments?

I really, really appreciate your help.

Thanks in advance!
